name: Deploy ServiceCycle

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.5'

      - name: Install dependencies
        run: npm install

      - name: Build ServiceCycle
        run: npm run build

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo -e "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ls -lah private_key.pem
          file private_key.pem
          cat private_key.pem | head -n 5

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem -o IdentitiesOnly=yes root@23.94.83.27 "cd ~/dev/servicecycle && git pull && npm install && npm run build && pm2 restart servicecycle --update-env"
